---
chargen:
  achievements:
    created_character:
      type: story
      message: Created a character.
  allow_web_submit: true
  app_category: APP
  app_hold_status: HOLD
  app_notes_prompt: If you want to make any special notes about your application,
    you can enter them below. For Merit notes, custom Anchors, ability details, or
    other required template items (e.g., Touchstones, Frailties, etc.), please set
    these in the Ledger section of your character page, either in the appropriate
    sphere-specific tab, or in the Notes tab.
  app_resubmit_status: OPEN
  app_review_commands:
  - app %{name}
  - look %{name}
  - profile %{name}
  - bg %{name}
  - hooks %{name}
  - sheet %{name}
  approval_message: |-
    Congratulations! Your application has been approved. Type %xhonstage%xn to go forth and RP. You may want to customize your character profile on the web portal.
    You have automatically had your additional starter XP added! Please see [System](https://cityofglass.aresmush.com/wiki/system) for information on how to spend XP, and the [Equipment Guide](https://cityofglass.aresmush.com/wiki/equipment_guide) for how to request starter equipment.
  arrivals_category: New Arrivals
  bg_blurb: A background is your character's backstory or history. You don''t need
    to write a novel. Just cover the basics--who you are, why are you here, and anything
    noteworthy about you. Please keep backgrounds to 750 words or less.
  demographics_blurb: Demographics record your basic character info.
  desc_blurb: You can set both your main description, visible when people look at
    you, and a short description that shows your character at a glance.
  groups_blurb: This simply helps us tell how many people are in each template. It
    is how characters are sorted on the webpage listing as well.
  hooks_blurb: RP Hooks are interesting things about your character that others can
    hook into for RP. This could be an odd personality quirk, a reputation your character
    has, or anything else that might inspire someone to connect with you. Looking
    around at other character's sheets can be a good way to get inspiration for RP
    Hooks.
  hooks_required: true
  icon_blurb: Your profile icon appears in scenes and the character gallery to show
    your character at a glance. Providing a profile icon is optional. You can upload
    additional character images once you're approved.
  lastwill_blurb: The fate of idled-out characters is at the game admin's discretion,
    but you can register a preference with your character's 'last will'. You may ask
    to be killed off, or turned into a NPC, or whatever.
  max_bg_length: 4300
  permissions:
    manage_apps: Approve and reject character apps.
    view_bgs: Can view other characters' backgrounds
  post_approval_message: 
  rank_blurb: Military rank.
  rejection_message: Sorry, your character could not be approved at the present time
    for the reasons described below.
  shortcuts:
    chargen: cg
    cg/back: cg/prev
    cg/previous: cg/prev
    bg/approve: app/approve
    bg/reject: app/reject
    bg/submit: app/submit
    bg/unsubmit: app/unsubmit
    hooks: hook
    hook/delete: hook/remove
    hook/add: hook/set
  stages:
    start:
      title: Chargen Commands
      text: Our chargen is exclusive on the web portal. Please select `Create a Character`
        from the `Getting Started` menu to begin!
    app:
      title: App Review
      text: The `Review` button is your friend during chargen. It will alert you to
        things you may have forgotten to set.  %xrred%xn issues will almost certainly
        prevent your character from being approved (like forgetting to set your template).
        %xyYellow%xn issues are warnings; they might actually be OK if it fits the
        character concept.
    demographics:
      help: demographics
    background:
      help: backgrounds
    desc:
      help: descriptions
    hooks:
      help: hooks
    handles:
      help: handles
    profile:
      help: profile
    lastwill:
      help: idle_out
    review:
      title: App Submission
      text: You've completed chargen! Review your app one more time, and use `Submit`
        to submit your character when ready. The admins will make sure it's a good
        fit for the game's theme, that the skills are reasonable given the background,
        and that you haven't missed anything important in chargen. See `help apps`
        for additional help on the app review process.
  welcome_message: |-
    Please welcome %{name}, our newest %{template}!

    Profile: %{profile_link}

    RP Hooks:

    %{rp_hooks}
