---
cod:
  exploits:
  - name: Addictive Presence
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Socialize + Primum
    action: Extended (target number = target's Willpower
    book: Demon the Descent
    page: 158
  - name: Affliction
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Strength + Medicine + Primum vs (Stamina or Resolve) + Tolerance
    action: Instant
    book: Demon the Descent
    page: 159
  - name: Allies into Gold
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Intelligence + Socialize + Primum
    action: Extended (target number = number of dots being shifted; one roll/hour)
    book: Demon the Descent
    page: 159
  - name: Animate
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Crafts + Primum
    action: Instant
    book: Demon the Descent
    page: 161
  - name: Behind the Curtain
    group: Exploit
    has_spec: true
    cost: 2 Aether
    pool: Intelligence + Computer + Primum
    action: Instant
    book: Demon the Descent
    page: 161
  - name: Break the Dam
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Science + Primum - Stamina
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 110
  - name: Break to Heal
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Strength + Medicine + Primum
    action: Instant
    book: Demon the Descent
    page: 162
  - name: Context Matters
    group: Exploit
    has_spec: true
    cost: 2/5 Aether
    pool: Presence + Persuasion + Primum
    action: Instant or extended
    book: 'DtD: Flowers of Hell'
    page: 110
  - name: Decoy
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Stealth + Primum
    action: Instant
    book: 'DtD: Interface'
    page: 123
  - name: Deep Pockets
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Strength + Larceny + Primum
    action: Instant
    book: Demon the Descent
    page: 162
  - name: Demon Car
    group: Exploit
    has_spec: true
    cost: 1+ Aether
    pool: Strength + Drive + Primum
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 111
  - name: Demon House
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Stealth + Primum
    action: Instant
    book: Demon the Descent
    page: 162
  - name: Devour Infrastructure
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Strength + Survival + Primum
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 112
  - name: Disintegrate
    group: Exploit
    has_spec: true
    cost: 1(1) Aether
    pool: Strength + Brawl + Primum
    action: Reflexive
    book: Demon the Descent
    page: 163
  - name: Echoing Death
    group: Exploit
    has_spec: true
    cost: 2 Aether
    pool: Strength + Brawl + Primum
    action: Extended (required successes = lethal damage required to kill target;
      1 roll/turn)
    book: Demon the Descent
    page: 163
  - name: Ephemeral Cover
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Strength + Occult + Primum - Defense
    action: Instant
    book: Demon the Descent
    page: 164
  - name: Everybody Hates Him
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Intelligence + Intimidation + Primum
    action: Instant
    book: Demon the Descent
    page: 164
  - name: Extispicy
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Intelligence + Occult + Primum
    action: Extended (successes = creature's Health; one roll per turn)
    book: Demon the Descent
    page: 165
  - name: Eye for an Eye
    group: Exploit
    has_spec: true
    cost: 1 Aether (1/attack)
    pool: Strength + Medicine + Primum - Damage
    action: Instant
    book: 'DtD: Interface'
    page: 97
  - name: Force Relationship
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Empathy + Primum
    action: Extended (5 or 10 successes, one roll per hour)
    book: Demon the Descent
    page: 165
  - name: Four Minutes Ago
    group: Exploit
    has_spec: true
    cost: 2 Aether
    pool: Intelligence + Stealth + Primum
    action: Instant
    book: Demon the Descent
    page: 166
  - name: Frozen in Time
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Intelligence + Science + Primum - Stamina
    action: Instant
    book: Demon the Descent
    page: 166
  - name: Halo
    group: Exploit
    has_spec: true
    cost: 2 Aether
    pool: Presence + Medicine + Primum
    action: Instant
    book: Demon the Descent
    page: 167
  - name: Hellfire
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Firearms + Primum
    action: Reflexive
    book: Demon the Descent
    page: 167
  - name: Hellhounds
    group: Exploit
    has_spec: true
    cost: 1 Aether/Size
    pool: Intelligence + Animal Ken + Primum
    action: Instant
    book: Demon the Descent
    page: 167
  - name: Incendiary
    group: Exploit
    has_spec: true
    cost: 1 Aether (1/turn)
    pool: Strength + Science + Primum
    action: Reflexive
    book: Demon the Descent
    page: 168
  - name: Inflict Stigmata
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Occult + Primum
    action: Extended (target number = target's Integrity; one roll/turn)
    book: Demon the Descent
    page: 168
  - name: Living Installation
    group: Exploit
    has_spec: true
    cost: 2 Aether
    pool: Intelligence + Medicine + Primum
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 112
  - name: Living Shadow
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Intelligence + Stealth + Primum
    action: Instant
    book: Demon the Descent
    page: 169
  - name: Merge
    group: Exploit
    has_spec: true
    cost: 1/demon
    pool: Strength + Occult + Primum
    action: Instant
    book: Demon the Descent
    page: 169
  - name: Murder by Improbability
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Intelligence + Academics + Primum vs Presence + Tolerance
    action: Instant
    book: Demon the Descent
    page: 170
  - name: Newton's Nightmares
    group: Exploit
    has_spec: true
    cost: 3 Aether
    pool: Intelligence + Science + Primum
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 112
  - name: Open-and-Shut Case
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Investigation + Primum
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 114
  - name: Play on Words
    group: Exploit
    has_spec: true
    cost: 2 Aether
    pool: Presence + Expression + Primum
    action: Reflexive
    book: Demon the Descent
    page: 170
  - name: Possession
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Intelligence + Persuasion + Primum - Resolve
    action: Instant
    book: Demon the Descent
    page: 171
  - name: Rain of Blood
    group: Exploit
    has_spec: true
    cost: 3 Aether
    pool: Strength + Occult + Primum
    action: Instant
    book: Demon the Descent
    page: 172
  - name: Raise Dead
    group: Exploit
    has_spec: true
    cost: 1 Aether/day
    pool: Presence + Medicine + Primum
    action: Extended (variable successes required, see below; one roll/day)
    book: Demon the Descent
    page: 172
  - name: Raze Infrastructure
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Streetwise + Primum
    action: Extended
    book: Demon the Descent
    page: 173
  - name: Reality Enforcement
    group: Exploit
    has_spec: true
    cost: 3 Aether
    pool: Presence + Academics + Primum
    action: Instant
    book: Demon the Descent
    page: 173
  - name: Riot
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Persuasion + Primum
    action: Instant
    book: Demon the Descent
    page: 174
  - name: Rip the Gates
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Strength + Occult + Primum
    action: Extended (3 successes required, one turn/roll)
    book: Demon the Descent
    page: 174
  - name: Sermon
    group: Exploit
    has_spec: true
    cost: 1 Aether/speech
    pool: Presence + Persuasion + Primum
    action: Extended (target number of successes = Integrity; one roll/day)
    book: Demon the Descent
    page: 175
  - name: Show of Power
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Occult + Primum vs Wits + Tolerance
    action: Instant and contested or reflexive and contested
    book: 'DtD: Flowers of Hell'
    page: 114
  - name: Solitary Confinement
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Strength + Occult + Primum - Resolve + Tolerance
    action: Instant
    book: Demon the Descent
    page: 176
  - name: Soul Brand
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Expression + Primum - Tolerance
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 115
  - name: Stalking Horse
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Expression + Primum vs Composure + Tolerance
    action: Instant
    book: Demon the Descent
    page: 176
  - name: Stimulus/Response
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Intelligence + Empathy + Primum vs Resolve + Tolerance
    action: Reflexive
    book: Demon the Descent
    page: 176
  - name: Stop
    group: Exploit
    has_spec: true
    cost: 2 Aether
    pool: Intelligence + Science + Primum
    action: Reflexive
    book: 'DtD: Flowers of Hell'
    page: 115
  - name: Summon
    group: Exploit
    has_spec: true
    cost: 1 Aether/day
    pool: Presence + Streetwise + Primum
    action: Instant
    book: Demon the Descent
    page: 177
  - name: Swarm
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Animal Ken + Primum
    action: Instant
    book: Demon the Descent
    page: 177
  - name: Swift Resolution
    group: Exploit
    has_spec: true
    cost: 3 Aether
    pool: Intelligence + Academics + Primum
    action: Instant
    book: Demon the Descent
    page: 178
  - name: Terrible Avatar
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Strength + Occult + Primum
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 116
  - name: Two Places at Once
    group: Exploit
    has_spec: true
    cost: 3 Aether
    pool: Presence + Science + Primum
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 116
  - name: Ultimatum
    group: Exploit
    has_spec: true
    cost: 2 Aether
    pool: Intelligence + Science + Primum vs Resolve
    action: Instant and contested
    book: 'DtD: Flowers of Hell'
    page: 116
  - name: Urban Legend
    group: Exploit
    has_spec: true
    cost: 1 Aether/roll
    pool: Intelligence + Expression + Primum
    action: Extended (one roll/week, 16 successes required)
    book: 'DtD: Flowers of Hell'
    page: 117
  - name: Visions of Heaven and Hell
    group: Exploit
    has_spec: true
    cost: 2 Aether
    pool: Presence + Intimidation + Primum vs Resolve + Tolerance
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 118
  - name: Walls of Jericho
    group: Exploit
    has_spec: true
    cost: 3 Aether
    pool: Strength + Intimidation + Primum
    action: Instant
    book: 'DtD: Flowers of Hell'
    page: 119
  - name: The Word
    group: Exploit
    has_spec: true
    cost: 1 Aether
    pool: Presence + Intimidation + Primum - Resolve
    action: Instant
    book: Demon the Descent
    page: 179
